targets:
  $default:
    builders:
      source_gen|combining_builder:
        generate_for:
          - lib/models/**.dart
          - lib/dto/**.dart
          - lib/data/rest_api_client/**.dart
        options:
          build_extensions:
            '^lib/models/{{}}.dart': 'lib/models/generated/{{}}.g.dart'
            '^lib/dto/{{}}.dart': 'lib/dto/generated/{{}}.g.dart'
            '^lib/data/rest_api_client/{{}}.dart': 'lib/data/rest_api_client/generated/{{}}.g.dart'
      freezed|freezed:
        enabled: true
        options:
          build_extensions:
            '^lib/models/{{}}.dart': 'lib/models/generated/{{}}.freezed.dart'
            '^lib/dto/{{}}.dart': 'lib/dto/generated/{{}}.freezed.dart'
