arb-dir: lib/utils/l10n
template-arb-file: app_ko.arb
output-localization-file: app_localizations.dart
untranslated-messages-file: untranslated_messages.txt
preferred-supported-locales:
  - ko
use-deferred-loading: true
suppress-warnings: true