name: woori
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter

  # Cloud bucket
  cloudflare_r2: ^0.0.10

  # Dialog
  panara_dialogs: ^0.1.5

  # Env
  flutter_dotenv: ^5.2.1

  # Freezed
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4

  # Http
  dio: ^5.7.0
  json_annotation: ^4.9.0
  retrofit: ^4.4.2

  # Icons
  cupertino_icons: ^1.0.8

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  # Media
  flutter_image_compress: ^2.3.0
  image_picker: ^1.1.2

  # Router
  go_router: ^14.6.2

  # Splash screen
  lottie: ^3.2.0

  # State management
  flutter_riverpod: ^2.6.1

  # Storage
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.4

  # Svg
  flutter_svg: ^2.0.16

  # Utils
  feedback: ^3.1.0
  path_provider: ^2.1.5
  talker: ^4.5.4
  camera: ^0.11.1
  share_plus: ^10.1.4
  flutter_phoenix: ^1.1.1
  timeago: ^3.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  # Build_runner
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  source_gen: ^1.5.0
  retrofit_generator: ^9.1.5
  flutter_gen_runner: ^5.9.0

  # Lint & Testing
  flutter_lints: ^4.0.0
  mockito: ^5.4.4


flutter_gen:
  output: lib/utils/image_generated/ # Optional (default: lib/gen/)
  line_length: 80

flutter:
  generate: true
  assets:
    - .env
    - assets/images/dash/

  uses-material-design: true

